# Generated by Django 4.2.21 on 2025-07-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_link_posted_by_mcq_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banned',
            field=models.BooleanField(default=False, help_text='Indicates whether the user is banned from the system.'),
        ),
    ]
