# Generated by Django 5.2.1 on 2025-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_student_university_id_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
