# Generated by Django 5.2.1 on 2025-05-09 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_student_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
