# Generated by Django 5.2.1 on 2025-05-09 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_student_university_id_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(error_messages={'blank': 'This field cannot be blank.', 'unique': 'This email address is already in use.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'unique': 'This username is already taken.'}, max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
