# Generated by Django 5.2.1 on 2025-05-09 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_student_email_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'unique': 'This ID has already been used.'}, max_length=9, unique=True, validators=[django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
