# Generated by Django 5.2.1 on 2025-05-10 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
