# Generated by Django 5.2.1 on 2025-06-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_semester_subject_topic_sheets_notes_mcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='semester',
        ),
    ]
