# Generated by Django 5.2.1 on 2025-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_topic_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(error_messages={'blank': 'This field cannot be blank.'}),
        ),
    ]
