# Generated by Django 5.2.1 on 2025-06-21 09:37

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_semester_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='mcq_a',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_b',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_c',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_d',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_file',
            field=cloudinary.models.CloudinaryField(error_messages={'blank': 'This field cannot be blank.'}, max_length=255, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='sheet_file',
            field=cloudinary.models.CloudinaryField(error_messages={'blank': 'This field cannot be blank.'}, max_length=255, verbose_name='file'),
        ),
    ]
