# Generated by Django 5.2.1 on 2025-06-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_mcq_mcq_a_alter_mcq_mcq_b_alter_mcq_mcq_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
