# Generated by Django 5.2.1 on 2025-06-22 23:31

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subject', chained_model_field='subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='mainApp.topic'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subject', chained_model_field='subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mainApp.topic'),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subject', chained_model_field='subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='mainApp.topic'),
        ),
    ]
