# Generated by Django 5.2.1 on 2025-06-27 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_mcq_topic_alter_notes_topic_alter_sheets_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('description', models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_a',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_b',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_c',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_d',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.'}, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
