# Generated by Django 5.2.1 on 2025-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_link_mcq_pending_alter_mcq_mcq_a_alter_mcq_mcq_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
