# Generated by Django 5.2.1 on 2025-06-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_link_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
